command:
  - "python"
  - "-m"
  - "uvicorn"
  - "backend.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: APP_ENV
    value: "dev"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "148ccb90800933a1"
  - name: DATABRICKS_CATALOG
    value: "smthumala_catalog"
  - name: DATABRICKS_SCHEMA
    value: "site_selection"
  - name: GENIE_SPACE_ID
    value: "01f11e5c69071fb08d1596cc4adf59fa"
  - name: SERVING_ENDPOINT
    value: "databricks-claude-sonnet-4-6"
  - name: CHAT_ENDPOINT
    value: "databricks-gemini-2-5-flash"
