/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteImport } from './routes/_sidebar'
import { Route as SidebarIndexRouteImport } from './routes/_sidebar/index'
import { Route as SidebarSitePlaygroundRouteImport } from './routes/_sidebar/site-playground'
import { Route as SidebarNetworkDiagnosticsRouteImport } from './routes/_sidebar/network-diagnostics'
import { Route as SidebarDataValidationRouteImport } from './routes/_sidebar/data-validation'
import { Route as SidebarDataExplorationRouteImport } from './routes/_sidebar/data-exploration'

const SidebarRoute = SidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarIndexRoute = SidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarSitePlaygroundRoute = SidebarSitePlaygroundRouteImport.update({
  id: '/site-playground',
  path: '/site-playground',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarNetworkDiagnosticsRoute =
  SidebarNetworkDiagnosticsRouteImport.update({
    id: '/network-diagnostics',
    path: '/network-diagnostics',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarDataValidationRoute = SidebarDataValidationRouteImport.update({
  id: '/data-validation',
  path: '/data-validation',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarDataExplorationRoute = SidebarDataExplorationRouteImport.update({
  id: '/data-exploration',
  path: '/data-exploration',
  getParentRoute: () => SidebarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarIndexRoute
  '/data-exploration': typeof SidebarDataExplorationRoute
  '/data-validation': typeof SidebarDataValidationRoute
  '/network-diagnostics': typeof SidebarNetworkDiagnosticsRoute
  '/site-playground': typeof SidebarSitePlaygroundRoute
}
export interface FileRoutesByTo {
  '/data-exploration': typeof SidebarDataExplorationRoute
  '/data-validation': typeof SidebarDataValidationRoute
  '/network-diagnostics': typeof SidebarNetworkDiagnosticsRoute
  '/site-playground': typeof SidebarSitePlaygroundRoute
  '/': typeof SidebarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar': typeof SidebarRouteWithChildren
  '/_sidebar/data-exploration': typeof SidebarDataExplorationRoute
  '/_sidebar/data-validation': typeof SidebarDataValidationRoute
  '/_sidebar/network-diagnostics': typeof SidebarNetworkDiagnosticsRoute
  '/_sidebar/site-playground': typeof SidebarSitePlaygroundRoute
  '/_sidebar/': typeof SidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-exploration'
    | '/data-validation'
    | '/network-diagnostics'
    | '/site-playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/data-exploration'
    | '/data-validation'
    | '/network-diagnostics'
    | '/site-playground'
    | '/'
  id:
    | '__root__'
    | '/_sidebar'
    | '/_sidebar/data-exploration'
    | '/_sidebar/data-validation'
    | '/_sidebar/network-diagnostics'
    | '/_sidebar/site-playground'
    | '/_sidebar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRoute: typeof SidebarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/': {
      id: '/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/site-playground': {
      id: '/_sidebar/site-playground'
      path: '/site-playground'
      fullPath: '/site-playground'
      preLoaderRoute: typeof SidebarSitePlaygroundRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/network-diagnostics': {
      id: '/_sidebar/network-diagnostics'
      path: '/network-diagnostics'
      fullPath: '/network-diagnostics'
      preLoaderRoute: typeof SidebarNetworkDiagnosticsRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/data-validation': {
      id: '/_sidebar/data-validation'
      path: '/data-validation'
      fullPath: '/data-validation'
      preLoaderRoute: typeof SidebarDataValidationRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/data-exploration': {
      id: '/_sidebar/data-exploration'
      path: '/data-exploration'
      fullPath: '/data-exploration'
      preLoaderRoute: typeof SidebarDataExplorationRouteImport
      parentRoute: typeof SidebarRoute
    }
  }
}

interface SidebarRouteChildren {
  SidebarDataExplorationRoute: typeof SidebarDataExplorationRoute
  SidebarDataValidationRoute: typeof SidebarDataValidationRoute
  SidebarNetworkDiagnosticsRoute: typeof SidebarNetworkDiagnosticsRoute
  SidebarSitePlaygroundRoute: typeof SidebarSitePlaygroundRoute
  SidebarIndexRoute: typeof SidebarIndexRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarDataExplorationRoute: SidebarDataExplorationRoute,
  SidebarDataValidationRoute: SidebarDataValidationRoute,
  SidebarNetworkDiagnosticsRoute: SidebarNetworkDiagnosticsRoute,
  SidebarSitePlaygroundRoute: SidebarSitePlaygroundRoute,
  SidebarIndexRoute: SidebarIndexRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SidebarRoute: SidebarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
